[proxies]

# trojan+ws
[[proxies.trojan]]
remarks_prefix = "①"
password = "5be5de1d-8653-4ce3-a600-2ca1af75bdb5"
host = "trojan1.username.workers.dev"
server_name = "trojan1.username.workers.dev"
path = "/"
random_ports = [80, 8080, 8880, 2052, 2082, 2086, 2095]  # 跟非tls的端口要保持一致

# trojan+ws+tls
[[proxies.trojan]]
remarks_prefix = "②"
password = "0195bf7c-d0d6-72ad-85c7-7a74e7db64f3"
host = "trojan2.pages.dev"
server_name = "trojan2.pages.dev"
path = "/"
random_ports = [443, 2053, 2083, 2087, 2096, 8443]       # 跟tls的端口要保持一致

# ——————————————————————————————————————————————————————————————————

# vless+ws
[[proxies.vless]]
remarks_prefix = "③"
uuid = "0195bf7c-f8c6-7add-aa36-a2145cc38ebb"
host = "vless1.username.workers.dev"
server_name = "vless1.username.workers.dev"
path = "/?ed=2048"
random_ports = [80, 8080, 8880, 2052, 2082, 2086, 2095]  # 跟非tls的端口要保持一致

# vless+ws+tls
[[proxies.vless]]
remarks_prefix = "④"
uuid = "0195bf7d-17d6-704c-bd6b-fa56710382cc"
host = "vless2.pages.dev"
server_name = "vless2.pages.dev"
path = "/?ed=2048"
random_ports = [443, 2053, 2083, 2087, 2096, 8443]      # 跟tls的端口要保持一致

# ——————————————————————————————————————————————————————————————————

# shadowsocks+v2ray-plugin+websocket+NTLS
[[proxies.ss]]
remarks_prefix = "⑤"
password = "none"                                       # 默认为none，不用管它，设置任何值都无效的
host = "ss1.pages.dev"                                  
# path = "/192.168.1.1-443"                             # 其它部署代码的，就使用这格式
path = "/192.168.1.1-443/SSSIG_value"                   # 这个是/PROXYIP/SSSIG，格式要保持一样，以前接触到的PROXYIP没有端口，添加433端口                  
tls = false                                             # tls = false 意思使用[80, 8080, 8880, 2052, 2082, 2086, 2095]的端口
random_ports = [80, 8080, 8880, 2052, 2082, 2086, 2095] # 跟非tls的端口要保持一致

# shadowsocks+v2ray-plugin+websocket+TLS
[[proxies.ss]]
remarks_prefix = "⑥"
password = "none"                                       # 默认为none，不用管它，设置任何值都无效的
host = "ss2.pages.dev"                                  
path = "/192.168.1.1-443/SSSIG_value"                   # SSSIG_value这个值，是这个值才能使用该节点
tls = true                                              # tls = true 意思使用[443, 2053, 2083, 2087, 2096, 8443]的端口
random_ports = [443, 2053, 2083, 2087, 2096, 8443]      # 跟tls的端口要保持一致

# ——————————————————————————————————————————————————————————————————

# 后面可以继续添加
# 推荐：trojan的配置在前面，vless的配置在后面，ss-v2ray在最后，可以在url中，传入id=1参数来定位，使用哪个配置
